name: Force Deploy to Vercel

on:
  workflow_dispatch:  # 수동 트리거 가능
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Vercel Deploy
      run: |
        echo "Triggering Vercel deployment..."
        curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_memunes-projects-palate" \
          -H "Content-Type: application/json" \
          -d '{"ref": "main"}' || echo "Direct API call failed"